<div class="entry-edit">
    <form id="edit_form" action="<?php echo Mage::helper('adminhtml')->getUrl('*/*/export'); ?>" method="get">
        <input type="hidden" name="form_key" value="<?php echo Mage::getSingleton('core/session')->getFormKey(); ?>" />
        <div class="entry-edit-head">
            <h4 class="icon-head head-edit-form fieldset-legend">Taxify Order Export</h4>
            <div class="form-buttons"></div>
        </div>
        <div class="fieldset " id="import_settings">
            <table cellspacing="0" class="actions">
                <tbody>
                    <tr>
                        <td class="a-left filter">
                            <div class="f-left">
                                <div>From:&nbsp;<input class="input-text no-changes required-entry" type="text" id="period_date_from" name="from" value="" style="width:5em"> <img src="/skin/adminhtml/default/default/images/grid-cal.gif" title="Select Date" id="period_date_from_trig" alt="Select Date" class="v-middle">&nbsp;&nbsp;</div>
                                <div id="period_date_from_advaice"></div>
                            </div>

                            <div class="f-left">
                                <div>To:&nbsp;<input class="input-text no-changes required-entry" type="text" id="period_date_to" name="to" value="" style="width:5em"> <img src="/skin/adminhtml/default/default/images/grid-cal.gif" class="v-middle" title="Select Date" id="period_date_to_trig" alt="Select Date">&nbsp;&nbsp;</div>
                                <div id="period_date_to_advaice"></div>
                            </div>

                            <div class="f-left">
                            <script type="text/javascript">
                                <!--
                                Calendar.setup({
                                inputField : 'period_date_from',
                                ifFormat : '%m/%e/%Y',
                                button : 'period_date_from_trig',
                                align : 'Bl',
                                singleClick : true
                                });
                                Calendar.setup({
                                inputField : 'period_date_to',
                                ifFormat : '%m/%e/%Y',
                                button : 'period_date_to_trig',
                                align : 'Bl',
                                singleClick : true
                                });
                                //-->
                            </script>
                        </td>
                    </tr>
                    <tr>
                        <td class="value">
                            <br />
                            <select name="order_statuses[]" class=" select multiselect" size="5" multiple="multiple">
                                <option value="complete">Complete</option>
                                <option value="pending">Pending</option>
                                <option value="processing">Processing</option>
                                <option value="canceled">Canceled</option>
                            </select>
                        </td>
                    </tr>
                    <tr>
                        <td class="a-left filter">
                            <br />
                            <button title="Refresh" type="submit" class="scalable task" onclick="gridProductsSoldJsObject.doFilter();" style=""><span><span><span>Export</span></span></span></button>
                        </td>
                    </tr>
                </tbody>
            </table>
        </div>
    </form>
</div>
